// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'analise_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$FosforoDataImpl _$$FosforoDataImplFromJson(Map<String, dynamic> json) =>
    _$FosforoDataImpl(
      pResina: (json['pResina'] as num?)?.toDouble(),
      pMehlich: (json['pMehlich'] as num?)?.toDouble(),
      pRemanescente: (json['pRemanescente'] as num?)?.toDouble(),
      fontePrincipal:
          $enumDecodeNullable(_$FontePEnumMap, json['fontePrincipal']) ??
              FonteP.resina,
    );

Map<String, dynamic> _$$FosforoDataImplToJson(_$FosforoDataImpl instance) =>
    <String, dynamic>{
      'pResina': instance.pResina,
      'pMehlich': instance.pMehlich,
      'pRemanescente': instance.pRemanescente,
      'fontePrincipal': _$FontePEnumMap[instance.fontePrincipal]!,
    };

const _$FontePEnumMap = {
  FonteP.resina: 'resina',
  FonteP.mehlich: 'mehlich',
};

_$AnaliseModelImpl _$$AnaliseModelImplFromJson(Map<String, dynamic> json) =>
    _$AnaliseModelImpl(
      id: json['id'] as String,
      userId: json['userId'] as String,
      fazenda: json['fazenda'] as String?,
      produtor: json['produtor'] as String?,
      talhao: json['talhao'] as String?,
      numeroAmostra: json['numeroAmostra'] as String? ?? '',
      laboratorio: json['laboratorio'] as String? ?? '',
      profundidade: json['profundidade'] as String? ?? '',
      dataColeta: json['dataColeta'] as String? ?? '',
      status: json['status'] as String? ?? '',
      cultura: json['cultura'] as String? ?? '',
      safra: json['safra'] as String? ?? '',
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      descricaoLocal: json['descricaoLocal'] as String?,
      pdfUrl: json['pdfUrl'] as String?,
      argila: (json['argila'] as num?)?.toDouble(),
      silte: (json['silte'] as num?)?.toDouble(),
      areiaTotal: (json['areiaTotal'] as num?)?.toDouble(),
      phAgua: (json['phAgua'] as num?)?.toDouble(),
      phSmp: (json['phSmp'] as num?)?.toDouble(),
      phCaCl2: (json['phCaCl2'] as num?)?.toDouble(),
      materiaOrganica: (json['materiaOrganica'] as num?)?.toDouble(),
      carbonoOrganico: (json['carbonoOrganico'] as num?)?.toDouble(),
      pMehlich: (json['pMehlich'] as num?)?.toDouble(),
      pResina: (json['pResina'] as num?)?.toDouble(),
      pRem: (json['pRem'] as num?)?.toDouble(),
      s020: (json['s020'] as num?)?.toDouble(),
      s2040: (json['s2040'] as num?)?.toDouble(),
      k: (json['k'] as num?)?.toDouble(),
      ca: (json['ca'] as num?)?.toDouble(),
      mg: (json['mg'] as num?)?.toDouble(),
      al: (json['al'] as num?)?.toDouble(),
      hMaisAl: (json['hMaisAl'] as num?)?.toDouble(),
      na: (json['na'] as num?)?.toDouble(),
      b: (json['b'] as num?)?.toDouble(),
      cu: (json['cu'] as num?)?.toDouble(),
      fe: (json['fe'] as num?)?.toDouble(),
      mn: (json['mn'] as num?)?.toDouble(),
      zn: (json['zn'] as num?)?.toDouble(),
      ni: (json['ni'] as num?)?.toDouble(),
      mo: (json['mo'] as num?)?.toDouble(),
      se: (json['se'] as num?)?.toDouble(),
      fontePrincipalP:
          $enumDecodeNullable(_$FontePEnumMap, json['fontePrincipalP']) ??
              FonteP.mehlich,
      createdAt: const TimestampConverter().fromJson(json['createdAt']),
      updatedAt: const TimestampConverter().fromJson(json['updatedAt']),
      h: (json['h'] as num?)?.toDouble(),
      ctcEfetiva: (json['ctcEfetiva'] as num?)?.toDouble(),
      ctc: (json['ctc'] as num?)?.toDouble(),
      sb: (json['sb'] as num?)?.toDouble(),
      vPercent: (json['vPercent'] as num?)?.toDouble(),
      mPercent: (json['mPercent'] as num?)?.toDouble(),
      osLaboratorio: json['osLaboratorio'] as String?,
      dataEmissao: json['dataEmissao'] as String?,
      consultor: json['consultor'] as String?,
      labTemplateId: json['labTemplateId'] as String?,
      unidadeNutrientes: json['unidadeNutrientes'] as String?,
      unidadeMO: json['unidadeMO'] as String?,
      unidadeTextura: json['unidadeTextura'] as String?,
      cascalho: (json['cascalho'] as num?)?.toDouble(),
      areiaGrossa: (json['areiaGrossa'] as num?)?.toDouble(),
      areiaFina: (json['areiaFina'] as num?)?.toDouble(),
      co: (json['co'] as num?)?.toDouble(),
      municipio: json['municipio'] as String?,
      responsavelTecnico: json['responsavelTecnico'] as String?,
      cnpjCliente: json['cnpjCliente'] as String?,
      pTotal: (json['pTotal'] as num?)?.toDouble(),
      classificacaoTextura: json['classificacaoTextura'] as String?,
      tipoSoloMapa: (json['tipoSoloMapa'] as num?)?.toInt(),
      solicitante: json['solicitante'] as String?,
      convenio: json['convenio'] as String?,
      creaResponsavel: json['creaResponsavel'] as String?,
      cnpjLaboratorio: json['cnpjLaboratorio'] as String?,
      dataInicioEnsaio: json['dataInicioEnsaio'] as String?,
      dataFimEnsaio: json['dataFimEnsaio'] as String?,
      matriculaImovel: json['matriculaImovel'] as String?,
      codigoInterno: json['codigoInterno'] as String?,
      codigoExternoAmostra: json['codigoExternoAmostra'] as String?,
      caMaisMg: (json['caMaisMg'] as num?)?.toDouble(),
      kMgDm3: (json['kMgDm3'] as num?)?.toDouble(),
      cuMehlich: (json['cuMehlich'] as num?)?.toDouble(),
      feMehlich: (json['feMehlich'] as num?)?.toDouble(),
      mnMehlich: (json['mnMehlich'] as num?)?.toDouble(),
      znMehlich: (json['znMehlich'] as num?)?.toDouble(),
      cuDtpa: (json['cuDtpa'] as num?)?.toDouble(),
      feDtpa: (json['feDtpa'] as num?)?.toDouble(),
      mnDtpa: (json['mnDtpa'] as num?)?.toDouble(),
      znDtpa: (json['znDtpa'] as num?)?.toDouble(),
      dataRecebimento: json['dataRecebimento'] as String?,
      numeroRelatorio: json['numeroRelatorio'] as String?,
      codigoVerificacao: json['codigoVerificacao'] as String?,
      codigoTalhao: json['codigoTalhao'] as String?,
      totalAmostras: (json['totalAmostras'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$AnaliseModelImplToJson(_$AnaliseModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'userId': instance.userId,
      'fazenda': instance.fazenda,
      'produtor': instance.produtor,
      'talhao': instance.talhao,
      'numeroAmostra': instance.numeroAmostra,
      'laboratorio': instance.laboratorio,
      'profundidade': instance.profundidade,
      'dataColeta': instance.dataColeta,
      'status': instance.status,
      'cultura': instance.cultura,
      'safra': instance.safra,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'descricaoLocal': instance.descricaoLocal,
      'pdfUrl': instance.pdfUrl,
      'argila': instance.argila,
      'silte': instance.silte,
      'areiaTotal': instance.areiaTotal,
      'phAgua': instance.phAgua,
      'phSmp': instance.phSmp,
      'phCaCl2': instance.phCaCl2,
      'materiaOrganica': instance.materiaOrganica,
      'carbonoOrganico': instance.carbonoOrganico,
      'pMehlich': instance.pMehlich,
      'pResina': instance.pResina,
      'pRem': instance.pRem,
      's020': instance.s020,
      's2040': instance.s2040,
      'k': instance.k,
      'ca': instance.ca,
      'mg': instance.mg,
      'al': instance.al,
      'hMaisAl': instance.hMaisAl,
      'na': instance.na,
      'b': instance.b,
      'cu': instance.cu,
      'fe': instance.fe,
      'mn': instance.mn,
      'zn': instance.zn,
      'ni': instance.ni,
      'mo': instance.mo,
      'se': instance.se,
      'fontePrincipalP': _$FontePEnumMap[instance.fontePrincipalP]!,
      'createdAt': const TimestampConverter().toJson(instance.createdAt),
      'updatedAt': const TimestampConverter().toJson(instance.updatedAt),
      'h': instance.h,
      'ctcEfetiva': instance.ctcEfetiva,
      'ctc': instance.ctc,
      'sb': instance.sb,
      'vPercent': instance.vPercent,
      'mPercent': instance.mPercent,
      'osLaboratorio': instance.osLaboratorio,
      'dataEmissao': instance.dataEmissao,
      'consultor': instance.consultor,
      'labTemplateId': instance.labTemplateId,
      'unidadeNutrientes': instance.unidadeNutrientes,
      'unidadeMO': instance.unidadeMO,
      'unidadeTextura': instance.unidadeTextura,
      'cascalho': instance.cascalho,
      'areiaGrossa': instance.areiaGrossa,
      'areiaFina': instance.areiaFina,
      'co': instance.co,
      'municipio': instance.municipio,
      'responsavelTecnico': instance.responsavelTecnico,
      'cnpjCliente': instance.cnpjCliente,
      'pTotal': instance.pTotal,
      'classificacaoTextura': instance.classificacaoTextura,
      'tipoSoloMapa': instance.tipoSoloMapa,
      'solicitante': instance.solicitante,
      'convenio': instance.convenio,
      'creaResponsavel': instance.creaResponsavel,
      'cnpjLaboratorio': instance.cnpjLaboratorio,
      'dataInicioEnsaio': instance.dataInicioEnsaio,
      'dataFimEnsaio': instance.dataFimEnsaio,
      'matriculaImovel': instance.matriculaImovel,
      'codigoInterno': instance.codigoInterno,
      'codigoExternoAmostra': instance.codigoExternoAmostra,
      'caMaisMg': instance.caMaisMg,
      'kMgDm3': instance.kMgDm3,
      'cuMehlich': instance.cuMehlich,
      'feMehlich': instance.feMehlich,
      'mnMehlich': instance.mnMehlich,
      'znMehlich': instance.znMehlich,
      'cuDtpa': instance.cuDtpa,
      'feDtpa': instance.feDtpa,
      'mnDtpa': instance.mnDtpa,
      'znDtpa': instance.znDtpa,
      'dataRecebimento': instance.dataRecebimento,
      'numeroRelatorio': instance.numeroRelatorio,
      'codigoVerificacao': instance.codigoVerificacao,
      'codigoTalhao': instance.codigoTalhao,
      'totalAmostras': instance.totalAmostras,
    };
