// ignore_for_file: non_constant_identifier_names

// ============================================================
// DADOS: Absorção de Nutrientes em Soja
// Autor: Raudinei Afonso
// Formato: Dart/Flutter
// Unidades: macronutrientes = kg/ton | micronutrientes = g/ton
// Valor 0.0 = dado indisponível (calculado por índice de exportação)
// ============================================================

/// Estádios fenológicos
const List<String> kStadios = ['V1-V3', 'V4', 'V5', 'R1', 'R3', 'R5', 'R6'];
const List<String> kStadiosKeys = ['V1_V3', 'V4', 'V5', 'R1', 'R3', 'R5', 'R6'];

/// Todos os nutrientes
const List<String> kMacronutrientes = ['N', 'P', 'K', 'Ca', 'Mg', 'S'];
const List<String> kMicronutrientes = [
  'B',
  'Cu',
  'Fe',
  'Mn',
  'Zn',
  'Mo',
  'Co',
  'Ni',
  'Se'
];

const Map<String, String> kNutrienteNomes = {
  'N': 'Nitrogênio (N)',
  'P': 'Fósforo (P₂O₅)',
  'K': 'Potássio (K)',
  'Ca': 'Cálcio (Ca)',
  'Mg': 'Magnésio (Mg)',
  'S': 'Enxofre (S)',
  'B': 'Boro (B)',
  'Cu': 'Cobre (Cu)',
  'Fe': 'Ferro (Fe)',
  'Mn': 'Manganês (Mn)',
  'Zn': 'Zinco (Zn)',
  'Mo': 'Molibdênio (Mo)',
  'Co': 'Cobalto (Co)',
  'Ni': 'Níquel (Ni)',
  'Se': 'Selênio (Se)',
};

// ─── CURVAS DE ABSORÇÃO (% acumulado por estádio) ────────────
const Map<String, Map<String, double>> kAbsorcaoPercentuais = {
  'N': {
    'V1_V3': 10,
    'V4': 25,
    'V5': 40,
    'R1': 55,
    'R3': 75,
    'R5': 90,
    'R6': 97.5
  },
  'P': {
    'V1_V3': 7.5,
    'V4': 17.5,
    'V5': 30,
    'R1': 45,
    'R3': 70,
    'R5': 90,
    'R6': 97.5
  },
  'K': {
    'V1_V3': 12.5,
    'V4': 30,
    'V5': 52.5,
    'R1': 70,
    'R3': 87.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'Ca': {
    'V1_V3': 7.5,
    'V4': 25,
    'V5': 45,
    'R1': 65,
    'R3': 85,
    'R5': 97.5,
    'R6': 97.5
  },
  'Mg': {
    'V1_V3': 12.5,
    'V4': 35,
    'V5': 55,
    'R1': 75,
    'R3': 92.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'S': {
    'V1_V3': 15,
    'V4': 35,
    'V5': 55,
    'R1': 75,
    'R3': 92.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'B': {
    'V1_V3': 7.5,
    'V4': 25,
    'V5': 45,
    'R1': 65,
    'R3': 87.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'Cu': {
    'V1_V3': 7.5,
    'V4': 25,
    'V5': 45,
    'R1': 65,
    'R3': 87.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'Fe': {
    'V1_V3': 7.5,
    'V4': 25,
    'V5': 45,
    'R1': 65,
    'R3': 87.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'Mn': {
    'V1_V3': 7.5,
    'V4': 25,
    'V5': 45,
    'R1': 65,
    'R3': 87.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'Zn': {
    'V1_V3': 7.5,
    'V4': 25,
    'V5': 45,
    'R1': 65,
    'R3': 87.5,
    'R5': 97.5,
    'R6': 97.5
  },
  'Mo': {
    'V1_V3': 3.5,
    'V4': 12.5,
    'V5': 25,
    'R1': 40,
    'R3': 77.5,
    'R5': 92.5,
    'R6': 97.5
  },
  'Co': {
    'V1_V3': 3.5,
    'V4': 12.5,
    'V5': 25,
    'R1': 40,
    'R3': 77.5,
    'R5': 92.5,
    'R6': 97.5
  },
  'Ni': {
    'V1_V3': 3.5,
    'V4': 12.5,
    'V5': 25,
    'R1': 40,
    'R3': 77.5,
    'R5': 92.5,
    'R6': 97.5
  },
  'Se': {
    'V1_V3': 3.5,
    'V4': 12.5,
    'V5': 25,
    'R1': 40,
    'R3': 77.5,
    'R5': 92.5,
    'R6': 97.5
  },
};

// ─── ÍNDICES DE EXPORTAÇÃO ────────────────────────────────────
class IndiceExportacao {
  final double min;
  final double max;
  const IndiceExportacao(this.min, this.max);
  String get descricao =>
      '${min.toStringAsFixed(0)}–${max.toStringAsFixed(0)}%';
}

const Map<String, IndiceExportacao> kIndicesExportacao = {
  'N': IndiceExportacao(50, 70),
  'P': IndiceExportacao(70, 90),
  'K': IndiceExportacao(50, 60),
  'Ca': IndiceExportacao(10, 20),
  'Mg': IndiceExportacao(20, 30),
  'S': IndiceExportacao(20, 40),
  'B': IndiceExportacao(20, 30),
  'Cu': IndiceExportacao(25, 35),
  'Fe': IndiceExportacao(15, 25),
  'Mn': IndiceExportacao(5, 10),
  'Zn': IndiceExportacao(25, 35),
  'Mo': IndiceExportacao(20, 40),
  'Co': IndiceExportacao(40, 50),
  'Ni': IndiceExportacao(20, 30),
  'Se': IndiceExportacao(60, 85),
};

// ─── MODELO DE DADOS ──────────────────────────────────────────
class NutrientRecord {
  final double N, P, K, Ca, Mg, S, B, Cu, Fe, Mn, Zn, Mo, Co, Ni, Se;
  const NutrientRecord({
    required this.N,
    required this.P,
    required this.K,
    required this.Ca,
    required this.Mg,
    required this.S,
    required this.B,
    required this.Cu,
    required this.Fe,
    required this.Mn,
    required this.Zn,
    required this.Mo,
    required this.Co,
    required this.Ni,
    required this.Se,
  });

  double operator [](String key) => switch (key) {
        'N' => N,
        'P' => P,
        'K' => K,
        'Ca' => Ca,
        'Mg' => Mg,
        'S' => S,
        'B' => B,
        'Cu' => Cu,
        'Fe' => Fe,
        'Mn' => Mn,
        'Zn' => Zn,
        'Mo' => Mo,
        'Co' => Co,
        'Ni' => Ni,
        'Se' => Se,
        _ => 0.0,
      };
}

class SourceData {
  final NutrientRecord exportacao;
  final NutrientRecord extracao;
  const SourceData({required this.exportacao, required this.extracao});
}

// ─── BANCO DE DADOS PRINCIPAL ─────────────────────────────────
// Estrutura: { tipoFonte: { fonte: SourceData } }

final Map<String, Map<String, SourceData>> kNutrientData = {
  // ══════════════════════════════════════════════
  // AUTORES
  // ══════════════════════════════════════════════
  'Autores': {
    'Araújo (2023)': const SourceData(
      exportacao: NutrientRecord(
          N: 41.36,
          P: 3.40,
          K: 9.93,
          Ca: 0.60,
          Mg: 0.86,
          S: 1.28,
          B: 12.38,
          Cu: 4.32,
          Fe: 8.93,
          Mn: 4.28,
          Zn: 15.64,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 59.94,
          P: 5.23,
          K: 18.74,
          Ca: 2.39,
          Mg: 2.70,
          S: 2.98,
          B: 32.58,
          Cu: 8.63,
          Fe: 44.67,
          Mn: 21.41,
          Zn: 31.28,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Kurihara et al. (2013) — Exportação': const SourceData(
      exportacao: NutrientRecord(
          N: 42.33,
          P: 3.83,
          K: 7.29,
          Ca: 0.61,
          Mg: 0.54,
          S: 2.78,
          B: 10.07,
          Cu: 13.48,
          Fe: 15.51,
          Mn: 5.39,
          Zn: 31.66,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 0,
          P: 0,
          K: 0,
          Ca: 0,
          Mg: 0,
          S: 0,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Kurihara et al. (2013)138 — Extração': const SourceData(
      exportacao: NutrientRecord(
          N: 0,
          P: 0,
          K: 0,
          Ca: 0,
          Mg: 0,
          S: 0,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 61.35,
          P: 5.89,
          K: 13.76,
          Ca: 2.13,
          Mg: 2.39,
          S: 5.96,
          B: 26.23,
          Cu: 26.92,
          Fe: 78.00,
          Mn: 27.10,
          Zn: 63.15,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Santos et al. (2008)': const SourceData(
      exportacao: NutrientRecord(
          N: 46.62,
          P: 2.61,
          K: 10.52,
          Ca: 0.74,
          Mg: 0.75,
          S: 0.89,
          B: 9.11,
          Cu: 27.39,
          Fe: 29.81,
          Mn: 5.86,
          Zn: 27.28,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 67.57,
          P: 4.02,
          K: 19.84,
          Ca: 3.30,
          Mg: 2.81,
          S: 2.06,
          B: 23.09,
          Cu: 52.98,
          Fe: 149.08,
          Mn: 30.85,
          Zn: 53.38,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Bataglia & Mascarenhas (1977)': const SourceData(
      exportacao: NutrientRecord(
          N: 76.00,
          P: 5.70,
          K: 32.00,
          Ca: 1.90,
          Mg: 2.90,
          S: 3.10,
          B: 77.00,
          Cu: 26.00,
          Fe: 46.00,
          Mn: 13.00,
          Zn: 61.00,
          Mo: 6,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 64.00,
          P: 4.70,
          K: 18.00,
          Ca: 11.60,
          Mg: 6.70,
          S: 0,
          B: 24.00,
          Cu: 14.00,
          Fe: 115.00,
          Mn: 43.00,
          Zn: 43.00,
          Mo: 5,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Borkert (1986)': const SourceData(
      exportacao: NutrientRecord(
          N: 82.00,
          P: 7.50,
          K: 24.50,
          Ca: 11.80,
          Mg: 7.40,
          S: 15.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 51.00,
          P: 7.60,
          K: 17.00,
          Ca: 3.30,
          Mg: 3.50,
          S: 5.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 5,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Cordeiro et al. (1977)': const SourceData(
      exportacao: NutrientRecord(
          N: 77.40,
          P: 6.00,
          K: 32.00,
          Ca: 13.40,
          Mg: 4.00,
          S: 8.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 0,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 64.40,
          P: 5.00,
          K: 16.50,
          Ca: 2.90,
          Mg: 2.40,
          S: 8.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 5,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Darwich (1993)': const SourceData(
      exportacao: NutrientRecord(
          N: 82.00,
          P: 1.00,
          K: 4.00,
          Ca: 7.00,
          Mg: 7.80,
          S: 7.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 7,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 58.80,
          P: 5.20,
          K: 18.70,
          Ca: 1.90,
          Mg: 2.10,
          S: 3.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 5,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'EMBRAPA': const SourceData(
      exportacao: NutrientRecord(
          N: 83.00,
          P: 8.40,
          K: 25.00,
          Ca: 13.50,
          Mg: 7.30,
          S: 9.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 7,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 51.00,
          P: 1.00,
          K: 2.00,
          Ca: 3.10,
          Mg: 2.00,
          S: 5.00,
          B: 2,
          Cu: 1,
          Fe: 7,
          Mn: 3,
          Zn: 4,
          Mo: 5,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Portafos': const SourceData(
      exportacao: NutrientRecord(
          N: 83.00,
          P: 15.40,
          K: 38.00,
          Ca: 12.20,
          Mg: 7.30,
          S: 15.00,
          B: 0,
          Cu: 1,
          Fe: 0,
          Mn: 0,
          Zn: 4,
          Mo: 7,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 51.00,
          P: 1.00,
          K: 2.00,
          Ca: 3.10,
          Mg: 2.00,
          S: 5.00,
          B: 2,
          Cu: 1,
          Fe: 7,
          Mn: 3,
          Zn: 4,
          Mo: 5,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
    'Tanaka et al. (1994)': const SourceData(
      exportacao: NutrientRecord(
          N: 82.00,
          P: 7.50,
          K: 24.00,
          Ca: 12.00,
          Mg: 7.20,
          S: 15.00,
          B: 0,
          Cu: 0,
          Fe: 0,
          Mn: 0,
          Zn: 0,
          Mo: 7,
          Co: 0,
          Ni: 0,
          Se: 0),
      extracao: NutrientRecord(
          N: 51.00,
          P: 5.00,
          K: 17.00,
          Ca: 2.80,
          Mg: 2.00,
          S: 5.00,
          B: 2,
          Cu: 1,
          Fe: 218,
          Mn: 3,
          Zn: 4,
          Mo: 5,
          Co: 0,
          Ni: 0,
          Se: 0),
    ),
  },

  // ══════════════════════════════════════════════
  // GUIDORIZZI (por tecnologia)
  // ══════════════════════════════════════════════
  'Guidorizzi': {
    'Enlist': const SourceData(
      exportacao: NutrientRecord(
          N: 53.9,
          P: 9.3,
          K: 19.1,
          Ca: 2.2,
          Mg: 2.5,
          S: 6.7,
          B: 37.3,
          Cu: 10.9,
          Fe: 122.3,
          Mn: 14.1,
          Zn: 46.5,
          Mo: 3.2,
          Co: 0.2,
          Ni: 0.4,
          Se: 1.3),
      extracao: NutrientRecord(
          N: 142.9,
          P: 31.9,
          K: 120.8,
          Ca: 35.8,
          Mg: 13.6,
          S: 17.9,
          B: 163.9,
          Cu: 37.5,
          Fe: 726.3,
          Mn: 195.4,
          Zn: 159.7,
          Mo: 12.4,
          Co: 0.4,
          Ni: 1.9,
          Se: 1.5),
    ),
    'Xtend': const SourceData(
      exportacao: NutrientRecord(
          N: 55.1,
          P: 10.9,
          K: 19.6,
          Ca: 2.3,
          Mg: 2.5,
          S: 8.6,
          B: 38.7,
          Cu: 12.7,
          Fe: 246.7,
          Mn: 14.3,
          Zn: 44.8,
          Mo: 3.8,
          Co: 0.2,
          Ni: 0.5,
          Se: 1.1),
      extracao: NutrientRecord(
          N: 179.9,
          P: 36.4,
          K: 127.6,
          Ca: 61.1,
          Mg: 18.9,
          S: 27.3,
          B: 179.8,
          Cu: 42.6,
          Fe: 1106.9,
          Mn: 309.9,
          Zn: 178.5,
          Mo: 9.2,
          Co: 0.5,
          Ni: 2.5,
          Se: 1.6),
    ),
    'Roundup Ready': const SourceData(
      exportacao: NutrientRecord(
          N: 55.6,
          P: 9.3,
          K: 20.6,
          Ca: 2.1,
          Mg: 2.6,
          S: 8.3,
          B: 34.6,
          Cu: 11.0,
          Fe: 123.1,
          Mn: 15.7,
          Zn: 43.8,
          Mo: 3.3,
          Co: 0.2,
          Ni: 0.6,
          Se: 1.7),
      extracao: NutrientRecord(
          N: 145.8,
          P: 29.4,
          K: 106.9,
          Ca: 43.5,
          Mg: 14.7,
          S: 22.2,
          B: 160.1,
          Cu: 32.8,
          Fe: 673.9,
          Mn: 198.4,
          Zn: 140.1,
          Mo: 13.2,
          Co: 0.5,
          Ni: 2.2,
          Se: 2.2),
    ),
  },

  // ══════════════════════════════════════════════
  // CULTIVAR (variedades genéticas)
  // ══════════════════════════════════════════════
  'Cultivar': {
    '73i75RSF': const SourceData(
        exportacao: NutrientRecord(
            N: 57.2,
            P: 5.5,
            K: 19.0,
            Ca: 2.2,
            Mg: 2.9,
            S: 2.9,
            B: 3.9,
            Cu: 9.7,
            Fe: 31.1,
            Mn: 2.5,
            Zn: 31.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 82.9,
            P: 8.46,
            K: 35.85,
            Ca: 8.8,
            Mg: 9.06,
            S: 6.74,
            B: 10.26,
            Cu: 19.4,
            Fe: 155.5,
            Mn: 12.5,
            Zn: 63.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    '75i74RSF': const SourceData(
        exportacao: NutrientRecord(
            N: 56.4,
            P: 5.1,
            K: 17.1,
            Ca: 2.3,
            Mg: 2.8,
            S: 3.0,
            B: 36.6,
            Cu: 1.1,
            Fe: 285.3,
            Mn: 2.8,
            Zn: 3.7,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 81.74,
            P: 7.85,
            K: 32.26,
            Ca: 9.2,
            Mg: 8.75,
            S: 6.98,
            B: 96.32,
            Cu: 2.2,
            Fe: 1426.5,
            Mn: 14.0,
            Zn: 7.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    '77EA40': const SourceData(
        exportacao: NutrientRecord(
            N: 57.6,
            P: 5.1,
            K: 17.1,
            Ca: 2.3,
            Mg: 2.7,
            S: 2.7,
            B: 31.3,
            Cu: 8.5,
            Fe: 51.3,
            Mn: 18.6,
            Zn: 27.9,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.48,
            P: 7.85,
            K: 32.26,
            Ca: 9.2,
            Mg: 8.44,
            S: 6.28,
            B: 82.37,
            Cu: 17.0,
            Fe: 256.5,
            Mn: 93.0,
            Zn: 55.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'ADV4681 Ipro SR1': const SourceData(
        exportacao: NutrientRecord(
            N: 62.9,
            P: 5.5,
            K: 19.3,
            Ca: 2.5,
            Mg: 3.0,
            S: 3.0,
            B: 35.0,
            Cu: 8.1,
            Fe: 29.2,
            Mn: 24.4,
            Zn: 49.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 91.16,
            P: 8.46,
            K: 36.42,
            Ca: 10.0,
            Mg: 9.38,
            S: 6.98,
            B: 92.11,
            Cu: 16.2,
            Fe: 146.0,
            Mn: 122.0,
            Zn: 98.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'ADV4681 Ipro SR2': const SourceData(
        exportacao: NutrientRecord(
            N: 6.0,
            P: 5.5,
            K: 21.0,
            Ca: 2.3,
            Mg: 2.9,
            S: 3.2,
            B: 31.9,
            Cu: 8.4,
            Fe: 26.0,
            Mn: 23.1,
            Zn: 42.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 8.7,
            P: 8.46,
            K: 39.62,
            Ca: 9.2,
            Mg: 9.06,
            S: 7.44,
            B: 83.95,
            Cu: 16.8,
            Fe: 130.0,
            Mn: 115.5,
            Zn: 84.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'ADV4681 Ipro SR3': const SourceData(
        exportacao: NutrientRecord(
            N: 63.8,
            P: 5.4,
            K: 2.7,
            Ca: 2.4,
            Mg: 2.7,
            S: 3.1,
            B: 31.8,
            Cu: 8.4,
            Fe: 17.2,
            Mn: 43.9,
            Zn: 37.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 92.46,
            P: 8.31,
            K: 5.09,
            Ca: 9.6,
            Mg: 8.44,
            S: 7.21,
            B: 83.68,
            Cu: 16.8,
            Fe: 86.0,
            Mn: 219.5,
            Zn: 74.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'AS3595i2x': const SourceData(
        exportacao: NutrientRecord(
            N: 66.9,
            P: 5.7,
            K: 19.2,
            Ca: 3.0,
            Mg: 3.3,
            S: 3.1,
            B: 35.4,
            Cu: 1.0,
            Fe: 34.5,
            Mn: 22.7,
            Zn: 35.1,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 96.96,
            P: 8.77,
            K: 36.23,
            Ca: 12.0,
            Mg: 10.31,
            S: 7.21,
            B: 93.16,
            Cu: 2.0,
            Fe: 172.5,
            Mn: 113.5,
            Zn: 70.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'AS3640i2x': const SourceData(
        exportacao: NutrientRecord(
            N: 62.1,
            P: 5.6,
            K: 19.3,
            Ca: 1.7,
            Mg: 2.4,
            S: 3.2,
            B: 33.7,
            Cu: 8.8,
            Fe: 76.0,
            Mn: 18.8,
            Zn: 32.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 90.0,
            P: 8.62,
            K: 36.42,
            Ca: 6.8,
            Mg: 7.5,
            S: 7.44,
            B: 88.68,
            Cu: 17.6,
            Fe: 380.0,
            Mn: 94.0,
            Zn: 65.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'AS3700XTD': const SourceData(
        exportacao: NutrientRecord(
            N: 59.4,
            P: 5.2,
            K: 18.6,
            Ca: 2.3,
            Mg: 2.3,
            S: 3.1,
            B: 29.8,
            Cu: 8.1,
            Fe: 48.5,
            Mn: 19.0,
            Zn: 27.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 86.09,
            P: 8.0,
            K: 35.09,
            Ca: 9.2,
            Mg: 7.19,
            S: 7.21,
            B: 78.42,
            Cu: 16.2,
            Fe: 242.5,
            Mn: 95.0,
            Zn: 55.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'AS3707I2X': const SourceData(
        exportacao: NutrientRecord(
            N: 59.9,
            P: 5.5,
            K: 19.3,
            Ca: 2.1,
            Mg: 2.5,
            S: 3.1,
            B: 3.4,
            Cu: 8.2,
            Fe: 29.8,
            Mn: 2.5,
            Zn: 28.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 86.81,
            P: 8.46,
            K: 36.42,
            Ca: 8.4,
            Mg: 7.81,
            S: 7.21,
            B: 8.95,
            Cu: 16.4,
            Fe: 149.0,
            Mn: 12.5,
            Zn: 57.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'AS3790i2x': const SourceData(
        exportacao: NutrientRecord(
            N: 61.5,
            P: 4.8,
            K: 18.0,
            Ca: 2.0,
            Mg: 2.5,
            S: 2.9,
            B: 28.7,
            Cu: 8.4,
            Fe: 58.7,
            Mn: 21.0,
            Zn: 25.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 89.13,
            P: 7.38,
            K: 33.96,
            Ca: 8.0,
            Mg: 7.81,
            S: 6.74,
            B: 75.53,
            Cu: 16.8,
            Fe: 293.5,
            Mn: 105.0,
            Zn: 50.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'CREDENZ CZ37B39': const SourceData(
        exportacao: NutrientRecord(
            N: 6.7,
            P: 5.4,
            K: 18.3,
            Ca: 2.5,
            Mg: 2.9,
            S: 3.0,
            B: 34.7,
            Cu: 1.8,
            Fe: 35.9,
            Mn: 2.0,
            Zn: 3.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 9.71,
            P: 8.31,
            K: 34.53,
            Ca: 10.0,
            Mg: 9.06,
            S: 6.98,
            B: 91.32,
            Cu: 3.6,
            Fe: 179.5,
            Mn: 10.0,
            Zn: 6.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'CZ16B17 IPRO': const SourceData(
        exportacao: NutrientRecord(
            N: 62.4,
            P: 5.5,
            K: 18.4,
            Ca: 2.5,
            Mg: 2.6,
            S: 2.9,
            B: 3.8,
            Cu: 8.9,
            Fe: 52.0,
            Mn: 19.8,
            Zn: 31.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 90.43,
            P: 8.46,
            K: 34.72,
            Ca: 10.0,
            Mg: 8.13,
            S: 6.74,
            B: 10.0,
            Cu: 17.8,
            Fe: 260.0,
            Mn: 99.0,
            Zn: 62.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'CZ37B39 I2X': const SourceData(
        exportacao: NutrientRecord(
            N: 63.6,
            P: 5.1,
            K: 18.1,
            Ca: 2.6,
            Mg: 2.9,
            S: 3.3,
            B: 35.5,
            Cu: 9.0,
            Fe: 41.6,
            Mn: 22.9,
            Zn: 29.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 92.17,
            P: 7.85,
            K: 34.15,
            Ca: 10.4,
            Mg: 9.06,
            S: 7.67,
            B: 93.42,
            Cu: 18.0,
            Fe: 208.0,
            Mn: 114.5,
            Zn: 58.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'CZ37B43': const SourceData(
        exportacao: NutrientRecord(
            N: 61.8,
            P: 5.3,
            K: 18.5,
            Ca: 2.8,
            Mg: 3.1,
            S: 3.2,
            B: 34.0,
            Cu: 8.8,
            Fe: 3.5,
            Mn: 24.8,
            Zn: 27.5,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 89.57,
            P: 8.15,
            K: 34.91,
            Ca: 11.2,
            Mg: 9.69,
            S: 7.44,
            B: 89.47,
            Cu: 17.6,
            Fe: 17.5,
            Mn: 124.0,
            Zn: 55.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'CZ37B43 Ipro PM': const SourceData(
        exportacao: NutrientRecord(
            N: 61.1,
            P: 5.5,
            K: 18.6,
            Ca: 2.2,
            Mg: 3.1,
            S: 2.9,
            B: 3.3,
            Cu: 9.8,
            Fe: 41.1,
            Mn: 19.4,
            Zn: 31.9,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 88.55,
            P: 8.46,
            K: 35.09,
            Ca: 8.8,
            Mg: 9.69,
            S: 6.74,
            B: 8.68,
            Cu: 19.6,
            Fe: 205.5,
            Mn: 97.0,
            Zn: 63.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'CZ37B43 Ipro PO1': const SourceData(
        exportacao: NutrientRecord(
            N: 53.0,
            P: 5.3,
            K: 17.9,
            Ca: 2.4,
            Mg: 2.9,
            S: 2.8,
            B: 3.1,
            Cu: 7.8,
            Fe: 12.6,
            Mn: 14.8,
            Zn: 28.7,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 76.81,
            P: 8.15,
            K: 33.77,
            Ca: 9.6,
            Mg: 9.06,
            S: 6.51,
            B: 8.16,
            Cu: 15.6,
            Fe: 63.0,
            Mn: 74.0,
            Zn: 57.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'CZ37B43 Ipro PO2': const SourceData(
        exportacao: NutrientRecord(
            N: 57.9,
            P: 5.3,
            K: 18.3,
            Ca: 2.8,
            Mg: 2.7,
            S: 2.6,
            B: 32.8,
            Cu: 7.5,
            Fe: 22.0,
            Mn: 14.9,
            Zn: 29.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.91,
            P: 8.15,
            K: 34.53,
            Ca: 11.2,
            Mg: 8.44,
            S: 6.05,
            B: 86.32,
            Cu: 15.0,
            Fe: 110.0,
            Mn: 74.5,
            Zn: 58.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Dagma 7621': const SourceData(
        exportacao: NutrientRecord(
            N: 57.8,
            P: 5.0,
            K: 17.8,
            Ca: 2.2,
            Mg: 2.6,
            S: 3.0,
            B: 33.0,
            Cu: 9.1,
            Fe: 44.2,
            Mn: 21.5,
            Zn: 3.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.77,
            P: 7.69,
            K: 33.58,
            Ca: 8.8,
            Mg: 8.13,
            S: 6.98,
            B: 86.84,
            Cu: 18.2,
            Fe: 221.0,
            Mn: 107.5,
            Zn: 6.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Dagma 7921': const SourceData(
        exportacao: NutrientRecord(
            N: 6.0,
            P: 4.5,
            K: 18.2,
            Ca: 2.5,
            Mg: 2.9,
            S: 2.7,
            B: 28.0,
            Cu: 7.8,
            Fe: 47.0,
            Mn: 21.9,
            Zn: 27.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 8.7,
            P: 6.92,
            K: 34.34,
            Ca: 10.0,
            Mg: 9.06,
            S: 6.28,
            B: 73.68,
            Cu: 15.6,
            Fe: 235.0,
            Mn: 109.5,
            Zn: 55.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Desafio PER1': const SourceData(
        exportacao: NutrientRecord(
            N: 6.8,
            P: 5.0,
            K: 19.2,
            Ca: 2.1,
            Mg: 2.6,
            S: 3.1,
            B: 33.0,
            Cu: 1.4,
            Fe: 23.7,
            Mn: 19.9,
            Zn: 37.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 9.86,
            P: 7.69,
            K: 36.23,
            Ca: 8.4,
            Mg: 8.13,
            S: 7.21,
            B: 86.84,
            Cu: 2.8,
            Fe: 118.5,
            Mn: 99.5,
            Zn: 75.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'DESAFIO 8473 RFS': const SourceData(
        exportacao: NutrientRecord(
            N: 61.7,
            P: 4.5,
            K: 18.1,
            Ca: 2.5,
            Mg: 2.6,
            S: 2.9,
            B: 31.8,
            Cu: 7.8,
            Fe: 29.8,
            Mn: 23.1,
            Zn: 25.9,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 89.42,
            P: 6.92,
            K: 34.15,
            Ca: 10.0,
            Mg: 8.13,
            S: 6.74,
            B: 83.68,
            Cu: 15.6,
            Fe: 149.0,
            Mn: 115.5,
            Zn: 51.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Desafio RR BM1': const SourceData(
        exportacao: NutrientRecord(
            N: 57.8,
            P: 5.5,
            K: 22.3,
            Ca: 2.3,
            Mg: 3.0,
            S: 3.1,
            B: 31.9,
            Cu: 7.3,
            Fe: 17.3,
            Mn: 27.7,
            Zn: 48.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.77,
            P: 8.46,
            K: 42.08,
            Ca: 9.2,
            Mg: 9.38,
            S: 7.21,
            B: 83.95,
            Cu: 14.6,
            Fe: 86.5,
            Mn: 138.5,
            Zn: 96.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Desafio RR BM2': const SourceData(
        exportacao: NutrientRecord(
            N: 61.5,
            P: 5.2,
            K: 19.5,
            Ca: 2.3,
            Mg: 2.8,
            S: 3.1,
            B: 3.3,
            Cu: 6.0,
            Fe: 26.2,
            Mn: 18.7,
            Zn: 28.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 89.13,
            P: 8.0,
            K: 36.79,
            Ca: 9.2,
            Mg: 8.75,
            S: 7.21,
            B: 8.68,
            Cu: 12.0,
            Fe: 131.0,
            Mn: 93.5,
            Zn: 56.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Desafio RR PER2': const SourceData(
        exportacao: NutrientRecord(
            N: 58.2,
            P: 5.7,
            K: 2.3,
            Ca: 2.0,
            Mg: 2.6,
            S: 3.4,
            B: 34.6,
            Cu: 9.3,
            Fe: 16.7,
            Mn: 19.1,
            Zn: 4.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 84.35,
            P: 8.77,
            K: 4.34,
            Ca: 8.0,
            Mg: 8.13,
            S: 7.91,
            B: 91.05,
            Cu: 18.6,
            Fe: 83.5,
            Mn: 95.5,
            Zn: 8.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Desafio RR VM': const SourceData(
        exportacao: NutrientRecord(
            N: 57.8,
            P: 5.2,
            K: 19.6,
            Ca: 2.7,
            Mg: 2.6,
            S: 3.1,
            B: 31.6,
            Cu: 9.1,
            Fe: 22.7,
            Mn: 22.5,
            Zn: 34.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.77,
            P: 8.0,
            K: 36.98,
            Ca: 10.8,
            Mg: 8.13,
            S: 7.21,
            B: 83.16,
            Cu: 18.2,
            Fe: 113.5,
            Mn: 112.5,
            Zn: 68.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'DM 69IX69': const SourceData(
        exportacao: NutrientRecord(
            N: 59.9,
            P: 5.6,
            K: 18.2,
            Ca: 3.3,
            Mg: 2.8,
            S: 3.4,
            B: 32.0,
            Cu: 7.2,
            Fe: 3.1,
            Mn: 22.3,
            Zn: 25.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 86.81,
            P: 8.62,
            K: 34.34,
            Ca: 13.2,
            Mg: 8.75,
            S: 7.91,
            B: 84.21,
            Cu: 14.4,
            Fe: 15.5,
            Mn: 111.5,
            Zn: 51.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'DM 72IX74': const SourceData(
        exportacao: NutrientRecord(
            N: 61.3,
            P: 5.1,
            K: 18.1,
            Ca: 2.2,
            Mg: 2.7,
            S: 2.9,
            B: 28.4,
            Cu: 9.6,
            Fe: 31.6,
            Mn: 18.6,
            Zn: 29.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 88.84,
            P: 7.85,
            K: 34.15,
            Ca: 8.8,
            Mg: 8.44,
            S: 6.74,
            B: 74.74,
            Cu: 19.2,
            Fe: 158.0,
            Mn: 93.0,
            Zn: 58.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'DM 74K75': const SourceData(
        exportacao: NutrientRecord(
            N: 63.2,
            P: 4.7,
            K: 19.2,
            Ca: 2.2,
            Mg: 2.4,
            S: 3.0,
            B: 35.3,
            Cu: 7.6,
            Fe: 36.7,
            Mn: 19.8,
            Zn: 26.7,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 91.59,
            P: 7.23,
            K: 36.23,
            Ca: 8.8,
            Mg: 7.5,
            S: 6.98,
            B: 92.89,
            Cu: 15.2,
            Fe: 183.5,
            Mn: 99.0,
            Zn: 53.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'DM 76IX77': const SourceData(
        exportacao: NutrientRecord(
            N: 59.3,
            P: 4.7,
            K: 16.1,
            Ca: 2.2,
            Mg: 2.2,
            S: 2.9,
            B: 34.8,
            Cu: 8.0,
            Fe: 48.1,
            Mn: 21.5,
            Zn: 26.9,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 85.94,
            P: 7.23,
            K: 30.38,
            Ca: 8.8,
            Mg: 6.88,
            S: 6.74,
            B: 91.58,
            Cu: 16.0,
            Fe: 240.5,
            Mn: 107.5,
            Zn: 53.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Exata i2x': const SourceData(
        exportacao: NutrientRecord(
            N: 6.0,
            P: 5.4,
            K: 17.9,
            Ca: 2.1,
            Mg: 2.8,
            S: 2.9,
            B: 34.0,
            Cu: 7.7,
            Fe: 38.2,
            Mn: 19.1,
            Zn: 26.5,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 8.7,
            P: 8.31,
            K: 33.77,
            Ca: 8.4,
            Mg: 8.75,
            S: 6.74,
            B: 89.47,
            Cu: 15.4,
            Fe: 191.0,
            Mn: 95.5,
            Zn: 53.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'FOCO 74177 RFS': const SourceData(
        exportacao: NutrientRecord(
            N: 56.2,
            P: 5.5,
            K: 18.8,
            Ca: 2.6,
            Mg: 2.7,
            S: 3.1,
            B: 36.5,
            Cu: 8.4,
            Fe: 26.0,
            Mn: 21.9,
            Zn: 31.5,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 81.45,
            P: 8.46,
            K: 35.47,
            Ca: 10.4,
            Mg: 8.44,
            S: 7.21,
            B: 96.05,
            Cu: 16.8,
            Fe: 130.0,
            Mn: 109.5,
            Zn: 63.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Guepardo IPRO': const SourceData(
        exportacao: NutrientRecord(
            N: 63.2,
            P: 5.5,
            K: 17.6,
            Ca: 3.1,
            Mg: 2.6,
            S: 3.0,
            B: 29.1,
            Cu: 8.5,
            Fe: 32.6,
            Mn: 21.4,
            Zn: 3.5,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 91.59,
            P: 8.46,
            K: 33.21,
            Ca: 12.4,
            Mg: 8.13,
            S: 6.98,
            B: 76.58,
            Cu: 17.0,
            Fe: 163.0,
            Mn: 107.0,
            Zn: 7.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'HO PARAGUAÇU': const SourceData(
        exportacao: NutrientRecord(
            N: 57.5,
            P: 5.1,
            K: 17.8,
            Ca: 1.8,
            Mg: 2.4,
            S: 3.0,
            B: 35.0,
            Cu: 7.2,
            Fe: 38.1,
            Mn: 18.9,
            Zn: 25.5,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.33,
            P: 7.85,
            K: 33.58,
            Ca: 7.2,
            Mg: 7.5,
            S: 6.98,
            B: 92.11,
            Cu: 14.4,
            Fe: 190.5,
            Mn: 94.5,
            Zn: 51.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'HO TAQUARI': const SourceData(
        exportacao: NutrientRecord(
            N: 6.3,
            P: 4.9,
            K: 18.0,
            Ca: 2.3,
            Mg: 2.6,
            S: 2.9,
            B: 32.9,
            Cu: 1.3,
            Fe: 69.7,
            Mn: 2.8,
            Zn: 25.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 9.13,
            P: 7.54,
            K: 33.96,
            Ca: 9.2,
            Mg: 8.13,
            S: 6.74,
            B: 86.58,
            Cu: 2.6,
            Fe: 348.5,
            Mn: 14.0,
            Zn: 50.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Juruena Ipro SR1': const SourceData(
        exportacao: NutrientRecord(
            N: 54.3,
            P: 5.1,
            K: 21.8,
            Ca: 2.6,
            Mg: 2.5,
            S: 2.9,
            B: 32.9,
            Cu: 6.1,
            Fe: 1.3,
            Mn: 24.0,
            Zn: 34.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 78.7,
            P: 7.85,
            K: 41.13,
            Ca: 10.4,
            Mg: 7.81,
            S: 6.74,
            B: 86.58,
            Cu: 12.2,
            Fe: 6.5,
            Mn: 120.0,
            Zn: 68.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Juruena Ipro SR2': const SourceData(
        exportacao: NutrientRecord(
            N: 55.4,
            P: 5.3,
            K: 2.9,
            Ca: 2.8,
            Mg: 2.7,
            S: 2.8,
            B: 35.3,
            Cu: 7.5,
            Fe: 17.1,
            Mn: 22.4,
            Zn: 4.7,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 80.29,
            P: 8.15,
            K: 5.47,
            Ca: 11.2,
            Mg: 8.44,
            S: 6.51,
            B: 92.89,
            Cu: 15.0,
            Fe: 85.5,
            Mn: 112.0,
            Zn: 9.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Juruena Ipro SR3': const SourceData(
        exportacao: NutrientRecord(
            N: 58.0,
            P: 5.8,
            K: 21.8,
            Ca: 2.5,
            Mg: 2.6,
            S: 2.9,
            B: 39.6,
            Cu: 7.4,
            Fe: 15.1,
            Mn: 29.9,
            Zn: 44.9,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 84.06,
            P: 8.92,
            K: 41.13,
            Ca: 10.0,
            Mg: 8.13,
            S: 6.74,
            B: 104.21,
            Cu: 14.8,
            Fe: 75.5,
            Mn: 149.5,
            Zn: 89.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'K7922I2X': const SourceData(
        exportacao: NutrientRecord(
            N: 61.4,
            P: 5.0,
            K: 19.4,
            Ca: 2.2,
            Mg: 2.8,
            S: 3.1,
            B: 32.3,
            Cu: 1.0,
            Fe: 42.9,
            Mn: 21.2,
            Zn: 31.9,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 88.99,
            P: 7.69,
            K: 36.6,
            Ca: 8.8,
            Mg: 8.75,
            S: 7.21,
            B: 85.0,
            Cu: 2.0,
            Fe: 214.5,
            Mn: 106.0,
            Zn: 63.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'LENDARIA 80K80': const SourceData(
        exportacao: NutrientRecord(
            N: 6.7,
            P: 4.9,
            K: 19.1,
            Ca: 2.4,
            Mg: 2.5,
            S: 2.7,
            B: 25.1,
            Cu: 8.2,
            Fe: 78.6,
            Mn: 19.1,
            Zn: 27.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 9.71,
            P: 7.54,
            K: 36.04,
            Ca: 9.6,
            Mg: 7.81,
            S: 6.28,
            B: 66.05,
            Cu: 16.4,
            Fe: 393.0,
            Mn: 95.5,
            Zn: 55.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'M 6430 XTD': const SourceData(
        exportacao: NutrientRecord(
            N: 62.4,
            P: 4.8,
            K: 17.3,
            Ca: 3.0,
            Mg: 3.0,
            S: 3.1,
            B: 26.6,
            Cu: 7.7,
            Fe: 73.4,
            Mn: 22.4,
            Zn: 23.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 90.43,
            P: 7.38,
            K: 32.64,
            Ca: 12.0,
            Mg: 9.38,
            S: 7.21,
            B: 70.0,
            Cu: 15.4,
            Fe: 367.0,
            Mn: 112.0,
            Zn: 47.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'M6100 XTD': const SourceData(
        exportacao: NutrientRecord(
            N: 6.7,
            P: 5.3,
            K: 19.0,
            Ca: 2.0,
            Mg: 2.5,
            S: 2.9,
            B: 32.0,
            Cu: 8.9,
            Fe: 25.3,
            Mn: 18.8,
            Zn: 26.7,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 9.71,
            P: 8.15,
            K: 35.85,
            Ca: 8.0,
            Mg: 7.81,
            S: 6.74,
            B: 84.21,
            Cu: 17.8,
            Fe: 126.5,
            Mn: 94.0,
            Zn: 53.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'M6110 i2x': const SourceData(
        exportacao: NutrientRecord(
            N: 57.3,
            P: 5.6,
            K: 18.5,
            Ca: 2.2,
            Mg: 2.5,
            S: 2.9,
            B: 31.4,
            Cu: 9.6,
            Fe: 56.6,
            Mn: 22.0,
            Zn: 33.1,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.04,
            P: 8.62,
            K: 34.91,
            Ca: 8.8,
            Mg: 7.81,
            S: 6.74,
            B: 82.63,
            Cu: 19.2,
            Fe: 283.0,
            Mn: 110.0,
            Zn: 66.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'M6210 Ipro': const SourceData(
        exportacao: NutrientRecord(
            N: 58.6,
            P: 5.2,
            K: 19.9,
            Ca: 2.2,
            Mg: 2.6,
            S: 3.0,
            B: 31.3,
            Cu: 8.4,
            Fe: 28.8,
            Mn: 2.6,
            Zn: 28.7,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 84.93,
            P: 8.0,
            K: 37.55,
            Ca: 8.8,
            Mg: 8.13,
            S: 6.98,
            B: 82.37,
            Cu: 16.8,
            Fe: 144.0,
            Mn: 13.0,
            Zn: 57.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'NEO750': const SourceData(
        exportacao: NutrientRecord(
            N: 6.4,
            P: 4.9,
            K: 16.7,
            Ca: 2.5,
            Mg: 2.6,
            S: 2.9,
            B: 38.7,
            Cu: 9.0,
            Fe: 86.5,
            Mn: 2.7,
            Zn: 3.5,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 9.28,
            P: 7.54,
            K: 31.51,
            Ca: 10.0,
            Mg: 8.13,
            S: 6.74,
            B: 101.84,
            Cu: 18.0,
            Fe: 432.5,
            Mn: 13.5,
            Zn: 7.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'NEOGEN 680': const SourceData(
        exportacao: NutrientRecord(
            N: 61.3,
            P: 5.9,
            K: 18.8,
            Ca: 2.4,
            Mg: 2.4,
            S: 3.2,
            B: 34.9,
            Cu: 1.0,
            Fe: 4.6,
            Mn: 18.7,
            Zn: 29.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 88.84,
            P: 9.08,
            K: 35.47,
            Ca: 9.6,
            Mg: 7.5,
            S: 7.44,
            B: 91.84,
            Cu: 2.0,
            Fe: 23.0,
            Mn: 93.5,
            Zn: 58.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'NEOGEN 71E': const SourceData(
        exportacao: NutrientRecord(
            N: 59.2,
            P: 5.4,
            K: 17.8,
            Ca: 2.2,
            Mg: 2.8,
            S: 3.0,
            B: 28.6,
            Cu: 9.0,
            Fe: 143.1,
            Mn: 19.0,
            Zn: 29.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 85.8,
            P: 8.31,
            K: 33.58,
            Ca: 8.8,
            Mg: 8.75,
            S: 6.98,
            B: 75.26,
            Cu: 18.0,
            Fe: 715.5,
            Mn: 95.0,
            Zn: 58.0,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'NEOGEN 720': const SourceData(
        exportacao: NutrientRecord(
            N: 57.3,
            P: 5.3,
            K: 18.8,
            Ca: 2.7,
            Mg: 2.9,
            S: 3.0,
            B: 34.4,
            Cu: 9.6,
            Fe: 3.8,
            Mn: 22.9,
            Zn: 29.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 83.04,
            P: 8.15,
            K: 35.47,
            Ca: 10.8,
            Mg: 9.06,
            S: 6.98,
            B: 90.53,
            Cu: 19.2,
            Fe: 19.0,
            Mn: 114.5,
            Zn: 58.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'NEOGEN 770': const SourceData(
        exportacao: NutrientRecord(
            N: 59.3,
            P: 5.2,
            K: 16.3,
            Ca: 2.7,
            Mg: 2.7,
            S: 3.0,
            B: 38.0,
            Cu: 9.4,
            Fe: 51.0,
            Mn: 21.2,
            Zn: 32.2,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 85.94,
            P: 8.0,
            K: 30.75,
            Ca: 10.8,
            Mg: 8.44,
            S: 6.98,
            B: 100.0,
            Cu: 18.8,
            Fe: 255.0,
            Mn: 106.0,
            Zn: 64.4,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'Olimpo 80182 RFS': const SourceData(
        exportacao: NutrientRecord(
            N: 63.2,
            P: 4.6,
            K: 18.4,
            Ca: 2.6,
            Mg: 2.9,
            S: 2.6,
            B: 35.3,
            Cu: 8.8,
            Fe: 37.9,
            Mn: 19.9,
            Zn: 26.3,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 91.59,
            P: 7.08,
            K: 34.72,
            Ca: 10.4,
            Mg: 9.06,
            S: 6.05,
            B: 92.89,
            Cu: 17.6,
            Fe: 189.5,
            Mn: 99.5,
            Zn: 52.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
    'SUPERA i2x': const SourceData(
        exportacao: NutrientRecord(
            N: 62.9,
            P: 5.4,
            K: 17.7,
            Ca: 2.2,
            Mg: 2.7,
            S: 2.8,
            B: 29.3,
            Cu: 9.8,
            Fe: 37.9,
            Mn: 2.4,
            Zn: 29.8,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0),
        extracao: NutrientRecord(
            N: 91.16,
            P: 8.31,
            K: 33.4,
            Ca: 8.8,
            Mg: 8.44,
            S: 6.51,
            B: 77.11,
            Cu: 19.6,
            Fe: 189.5,
            Mn: 12.0,
            Zn: 59.6,
            Mo: 0,
            Co: 0,
            Ni: 0,
            Se: 0)),
  },
};

// ─── HELPERS ──────────────────────────────────────────────────

bool isMacro(String nutrient) => kMacronutrientes.contains(nutrient);

class AbsorcaoResult {
  final String stage;
  final double percentage;
  final double value;
  final String unit;
  const AbsorcaoResult({
    required this.stage,
    required this.percentage,
    required this.value,
    required this.unit,
  });
}

/// Calcula absorção por estádio fenológico
/// [mode]: 'accumulated' ou 'perStage'
List<AbsorcaoResult> calcAbsorcao({
  required String sourceType,
  required String source,
  required String nutrient,
  required String dataType, // 'Exportação' ou 'Extração'
  required double yieldTons,
  String mode = 'accumulated',
}) {
  final baseValue = kNutrientData[sourceType]?[source]?.let((s) =>
          dataType == 'Exportação'
              ? s.exportacao[nutrient]
              : s.extracao[nutrient]) ??
      0.0;

  final percentages = kAbsorcaoPercentuais[nutrient]!;
  final macro = isMacro(nutrient);
  final valuePerTon = macro ? baseValue : baseValue / 1000.0;
  final totalKg = valuePerTon * yieldTons;
  final unit = totalKg < 1.0 ? 'g' : 'kg';
  final multiplier = unit == 'g' ? 1000.0 : 1.0;

  return List.generate(kStadiosKeys.length, (index) {
    final key = kStadiosKeys[index];
    final cumPct = percentages[key]!;
    final prevPct = index > 0 ? percentages[kStadiosKeys[index - 1]]! : 0.0;
    final pct = mode == 'accumulated' ? cumPct : cumPct - prevPct;
    final value = (pct / 100.0) * totalKg * multiplier;
    return AbsorcaoResult(
      stage: kStadios[index],
      percentage: pct,
      value: double.parse(value.toStringAsFixed(4)),
      unit: unit,
    );
  });
}

List<String> getSourceTypes() => kNutrientData.keys.toList();
List<String> getSources(String sourceType) =>
    kNutrientData[sourceType]?.keys.toList() ?? [];

// Extension helper para encadear null-checks
extension NullableExtension<T> on T? {
  R? let<R>(R Function(T) block) => this != null ? block(this as T) : null;
}
