import 'package:soloforte/domain/entities/lab_template.dart';

/// Templates padrao dos laboratorios principais.
/// Carregados automaticamente na primeira inicializacao do app.
final List<LabTemplate> defaultLabTemplates = [

  // IBRA -- Instituto Brasileiro de Analises
  // Unidades confirmadas nos PDFs reais (OS 237526 e 235421)
  LabTemplate(
    id: 'ibra_default',
    nome: 'IBRA',
    keywords: const [
      'instituto brasileiro de analises',
      'ibra.com.br',
      'ibra',
      'carlos eduardo prieto',
      'sumare',
    ],
    unidadeK: UnidadeNutriente.mmolcDm3,
    unidadeCa: UnidadeNutriente.mmolcDm3,
    unidadeMg: UnidadeNutriente.mmolcDm3,
    unidadeAl: UnidadeNutriente.mmolcDm3,
    unidadeHAl: UnidadeNutriente.mmolcDm3,
    unidadeNa: UnidadeNutriente.mmolcDm3,
    unidadeCTC: UnidadeNutriente.mmolcDm3,
    unidadeSB: UnidadeNutriente.mmolcDm3,
    unidadeMO: UnidadeMO.gDm3,
    unidadeCOT: UnidadeMO.gDm3,
    unidadeTextura: UnidadeTextura.gKg,
    entregaCTC: true,
    entregaSB: true,
    entregaVPercent: true,
    entregaMPercent: true,
    entregaHidrogenioPuro: true,
    entregaH: true,
    entregaCtcEfetiva: false,
    entregaMicroMehlich: false,
    entregaMicroDtpa: true,
    umAmostraPorLaudo: false,
    entregaAreiasDetalhadas: false,
    entregaCascalho: false,
    entregaPhSMP: true,
    entregaPhAgua: false,
    entregaMo: false,
    entregaCo: false,
    entregaPTotal: false,
    entregaClassificacaoTextura: false,
    entregaTipoSoloMapa: false,
    separaSolicitanteProprietario: false,
    entregaTextura: true,
    micronutrientesPorAmostra: false,
    identificacaoComposta: false,
    isDefault: true,
    ativo: true,
    createdAt: DateTime(2025, 1, 1),
  ),

  // ─────────────────────────────────────────────────────────────────────────
  // EXATA BRASIL — Unidades BA, GO, MS, MT
  // Sistema: Software Ultra Lims
  // Unidades confirmadas nos PDFs reais
  // ─────────────────────────────────────────────────────────────────────────
  LabTemplate(
    id: 'exata_default',
    nome: 'Exata Brasil',
    keywords: const [
      'exata brasil',
      'exatabrasil.com.br',
      'exata brasil unidade ba',
      'exata brasil unidade go',
      'exata brasil unidade ms',
      'exata brasil unidade mt',
      'ultra lims',
      'marny alexandre',
      'crea go 7216',
      'software ultra lims',
    ],
    unidadeK: UnidadeNutriente.cmolcDm3,
    unidadeCa: UnidadeNutriente.cmolcDm3,
    unidadeMg: UnidadeNutriente.cmolcDm3,
    unidadeAl: UnidadeNutriente.cmolcDm3,
    unidadeHAl: UnidadeNutriente.cmolcDm3,
    unidadeNa: UnidadeNutriente.cmolcDm3,
    unidadeCTC: UnidadeNutriente.cmolcDm3,
    unidadeSB: UnidadeNutriente.cmolcDm3,
    unidadeMO: UnidadeMO.gDm3,
    unidadeCOT: UnidadeMO.gDm3,
    unidadeTextura: UnidadeTextura.gDm3,
    entregaMicroMehlich: true,
    entregaMicroDtpa: true,
    entregaPhAgua: true,
    entregaCaMaisMg: true,
    entregaKNH4Cl: true,
    entregaSB: false,
    entregaH: false,
    entregaHidrogenioPuro: false,
    entregaCTC: true,
    entregaVPercent: true,
    entregaMPercent: true,
    entregaCtcEfetiva: false,
    entregaPhSMP: true,
    entregaMo: false,
    entregaCo: false,
    entregaPTotal: false,
    entregaClassificacaoTextura: false,
    entregaTipoSoloMapa: false,
    separaSolicitanteProprietario: false,
    entregaTextura: true,
    micronutrientesPorAmostra: false,
    identificacaoComposta: false,
    umAmostraPorLaudo: false,
    entregaAreiasDetalhadas: false,
    entregaCascalho: false,
    isDefault: true,
    ativo: true,
    createdAt: DateTime(2025, 1, 1),
  ),

  // MB AGRONEGÓCIOS
  // Palmas - TO | lab@grupomb.agr.br
  LabTemplate(
    id: 'mb_default',
    nome: 'MB Agronegócios',
    keywords: const [
      'mb agronegocios',
      'mb agronegócios',
      'grupomb.agr.br',
      'mb agronegócios ltda',
      'maurício bassani',
      'mauricio bassani',
      'cfta: 25800951870',
      '13.423.484/0001-23',
      '504 sul, av. lo 11',
      'análise de solo - nº',
    ],
    unidadeK: UnidadeNutriente.cmolcDm3,
    unidadeCa: UnidadeNutriente.cmolcDm3,
    unidadeMg: UnidadeNutriente.cmolcDm3,
    unidadeAl: UnidadeNutriente.cmolcDm3,
    unidadeHAl: UnidadeNutriente.cmolcDm3,
    unidadeNa: UnidadeNutriente.cmolcDm3,
    unidadeCTC: UnidadeNutriente.cmolcDm3,
    unidadeSB: UnidadeNutriente.cmolcDm3,
    unidadeMO: UnidadeMO.percent,
    unidadeCOT: UnidadeMO.gDm3,
    unidadeTextura: UnidadeTextura.percent,
    entregaMicroMehlich: true,
    entregaMicroDtpa: false,
    umAmostraPorLaudo: true,
    entregaAreiasDetalhadas: true,
    entregaCascalho: true,
    entregaPhSMP: true,
    entregaPhAgua: false,
    entregaMo: true,
    entregaCo: true,
    entregaCTC: true,
    entregaSB: true,
    entregaVPercent: true,
    entregaMPercent: true,
    entregaH: false,
    entregaHidrogenioPuro: false,
    entregaCtcEfetiva: false,
    entregaCaMaisMg: false,
    entregaKNH4Cl: true,
    entregaPTotal: false,
    entregaClassificacaoTextura: false,
    entregaTipoSoloMapa: false,
    separaSolicitanteProprietario: false,
    entregaTextura: true,
    micronutrientesPorAmostra: false,
    identificacaoComposta: false,
    isDefault: true,
    ativo: true,
    createdAt: DateTime(2025, 1, 1),
  ),

  // SELLAR ANÁLISES AGRÍCOLAS
  // Executor: Lab. de Análises Agrícolas do Tocantins Ltda.
  // CNPJ: 17.985.831/0001-62 | Gurupi - TO
  // Acreditação: PAQLF Embrapa Solos
  LabTemplate(
    id: 'sellar_default',
    nome: 'Sellar',
    keywords: const [
      'sellar',
      'sellar análises agrícolas',
      'sellar analises agricolas',
      'laboratório de análises agrícolas do tocantins',
      'laboratorio de analises agricolas do tocantins',
      '17.985.831/0001-62',
      'laudo de análise solo',
      'laudo de analise solo',
      'número sellar',
      'numero sellar',
      'paqlf',
      'weberson ribeiro',
      '124003422',
    ],
    unidadeK: UnidadeNutriente.cmolcDm3,
    unidadeCa: UnidadeNutriente.cmolcDm3,
    unidadeMg: UnidadeNutriente.cmolcDm3,
    unidadeAl: UnidadeNutriente.cmolcDm3,
    unidadeHAl: UnidadeNutriente.cmolcDm3,
    unidadeNa: UnidadeNutriente.cmolcDm3,
    unidadeCTC: UnidadeNutriente.cmolcDm3,
    unidadeSB: UnidadeNutriente.cmolcDm3,
    // M.O. em dag/kg (= % numericamente, confirmado no rodape)
    unidadeMO: UnidadeMO.dagKg,
    unidadeCOT: UnidadeMO.dagKg,
    // Textura em g/kg (igual ao IBRA)
    unidadeTextura: UnidadeTextura.gKg,
    // Micronutrientes via DTPA (igual ao IBRA)
    entregaMicroMehlich: false,
    entregaMicroDtpa: true,
    // Campos especiais Sellar
    entregaCtcEfetiva: true,
    entregaPhAgua: true,
    entregaPTotal: true,
    entregaClassificacaoTextura: true,
    entregaTipoSoloMapa: true,
    separaSolicitanteProprietario: true,
    // Sellar entrega derivados calculados
    entregaCTC: true,
    entregaSB: true,
    entregaVPercent: true,
    entregaMPercent: true,
    // Sellar nao entrega
    entregaHidrogenioPuro: false,
    entregaCaMaisMg: false,
    entregaKNH4Cl: true,
    entregaH: false,
    entregaAreiasDetalhadas: false,
    entregaCascalho: false,
    entregaMo: false,
    entregaCo: false,
    umAmostraPorLaudo: false,
    entregaPhSMP: false,
    entregaTextura: true,
    micronutrientesPorAmostra: false,
    identificacaoComposta: false,
    isDefault: true,
    ativo: true,
    createdAt: DateTime(2025, 1, 1),
  ),

  // SOLUM LABORATORIO S.A.
  // Goiania - GO | www.solum.net.br
  LabTemplate(
    id: 'solum_default',
    nome: 'Solum',
    keywords: const [
      'solum laboratorio',
      'solum.net.br',
      'solum lab',
      'solum s.a.',
      'solum s/a',
      '07.797.217/0001-67',
      'laudo de analise de solo',
      'relatorio de analise',
    ],
    unidadeK: UnidadeNutriente.mmolcDm3,
    unidadeCa: UnidadeNutriente.mmolcDm3,
    unidadeMg: UnidadeNutriente.mmolcDm3,
    unidadeAl: UnidadeNutriente.mmolcDm3,
    unidadeHAl: UnidadeNutriente.mmolcDm3,
    unidadeNa: UnidadeNutriente.mmolcDm3,
    unidadeCTC: UnidadeNutriente.mmolcDm3,
    unidadeSB: UnidadeNutriente.mmolcDm3,
    unidadeMO: UnidadeMO.gDm3,
    unidadeCOT: UnidadeMO.gDm3,
    unidadeTextura: UnidadeTextura.gKg,
    // Solum nao entrega textura no laudo padrao
    entregaTextura: false,
    // Micros por amostra (nao agrupado)
    micronutrientesPorAmostra: true,
    // Identificacao composta (codigo interno + externo)
    identificacaoComposta: true,
    // pH: apenas SMP (sem pH agua)
    entregaPhAgua: false,
    entregaPhSMP: true,
    // Micronutrientes via DTPA
    entregaMicroMehlich: false,
    entregaMicroDtpa: true,
    // Hidrogenio puro separado
    entregaHidrogenioPuro: true,
    entregaH: true,
    // Derivados calculados
    entregaCTC: true,
    entregaSB: true,
    entregaVPercent: true,
    entregaMPercent: true,
    entregaCtcEfetiva: false,
    // Solum nao entrega
    entregaCaMaisMg: false,
    entregaKNH4Cl: false,
    entregaMo: false,
    entregaCo: false,
    entregaPTotal: false,
    entregaClassificacaoTextura: false,
    entregaTipoSoloMapa: false,
    separaSolicitanteProprietario: false,
    umAmostraPorLaudo: false,
    entregaAreiasDetalhadas: false,
    entregaCascalho: false,
    isDefault: true,
    ativo: true,
    createdAt: DateTime(2025, 1, 1),
  ),

];
