// File generated by FlutterFire CLI.
// Substitua os valores marcados com TODO após rodar:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=soloforte-106c8
//
// Documentação completa: 05_FIREBASE_CONFIG.md

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web não está configurado neste build. '
        'Rode flutterfire configure para gerar as chaves web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS não está configurado. Adicione o app no console Firebase '
          'e rode flutterfire configure.',
        );
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'Plataforma não suportada: $defaultTargetPlatform',
        );
    }
  }

  // ------------------------------------------------------------------ //
  //  iOS — chaves reais (projeto soloforte-106c8)
  // ------------------------------------------------------------------ //

  // Mantidos valores válidos já presentes no projeto.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8NPxIz0rw_bZ4xjlIzJkgo7xm3WK4qw',
    appId: '1:398774255712:ios:e09f038303a816b72cc305',
    messagingSenderId: '398774255712',
    projectId: 'soloforte-106c8',
    storageBucket: 'soloforte-106c8.firebasestorage.app',
    iosClientId:
        'SEU_IOS_CLIENT_ID', // TODO: cole o valor do GoogleService-Info.plist
    iosBundleId: 'com.soloforte.soloforte',
  );

  // ------------------------------------------------------------------ //
  //  Android — estrutura pronta, preencher após flutterfire configure
  // ------------------------------------------------------------------ //
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'TODO_ANDROID_API_KEY', // do google-services.json -> api_key[0].current_key
    appId:
        'TODO_ANDROID_APP_ID', // do google-services.json -> client[0].client_info.mobilesdk_app_id
    messagingSenderId:
        'TODO_SENDER_ID', // do google-services.json -> project_info.project_number
    projectId: 'soloforte-106c8',
    storageBucket: 'soloforte-106c8.appspot.com',
  );
}
