# Uncomment this line to define a global platform for your project
platform :ios, '15.0'
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require 'fileutils'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'AnaliseForte' do
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      if target.name == 'gRPC-Core'
        config.build_settings['MODULEMAP_FILE'] = 'Target Support Files/gRPC-Core/gRPC-Core.modulemap'
      end
      if target.name == 'FirebaseStorage'
        config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
      end
      
      cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
      config.build_settings['OTHER_CFLAGS'] = cflags + ' -Wno-error=non-modular-include-in-framework-module -Wno-non-modular-include-in-framework-module'
    end
    # Remove bad COMPILER_FLAGS injected by third party pods (like BoringSSL-GRPC)
    if target.respond_to?(:source_build_phase) && target.source_build_phase
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS']
          flags = flags.gsub('-GCC_WARN_INHIBIT_ALL_WARNINGS', '')
          file.settings['COMPILER_FLAGS'] = flags
        end
      end
    end
  end

  Dir.glob(File.join(__dir__, 'Pods', 'Target Support Files', '**', '*.xcconfig')).each do |xcconfig_path|
    content = File.read(xcconfig_path)
    updated = content.gsub(
      '${PODS_ROOT}/Headers/Private/grpc/gRPC-Core.modulemap',
      '${PODS_ROOT}/Target Support Files/gRPC-Core/gRPC-Core.modulemap'
    ).gsub(
      ' -weak_framework "FirebaseFirestoreInternal"',
      ''
    )

    next if updated == content
    File.write(xcconfig_path, updated)
  end

  [
    File.join(__dir__, 'Pods', 'gRPC-Core', 'src', 'core', 'lib', 'promise', 'detail', 'basic_seq.h'),
    File.join(__dir__, 'Pods', 'gRPC-C++', 'src', 'core', 'lib', 'promise', 'detail', 'basic_seq.h')
  ].each do |grpc_basic_seq_path|
    next unless File.exist?(grpc_basic_seq_path)

    basic_seq = File.read(grpc_basic_seq_path)
    patched_basic_seq = basic_seq.gsub(
      'Traits::template CallSeqFactory(f_, *cur_, std::move(arg))',
      'Traits::CallSeqFactory(f_, *cur_, std::move(arg))'
    )
    if patched_basic_seq != basic_seq
      FileUtils.chmod('u+w', grpc_basic_seq_path)
      File.write(grpc_basic_seq_path, patched_basic_seq)
    end
  end

  firebase_storage_patch_paths = [
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_storage', 'ios', 'Classes', 'FLTTaskStateChannelStreamHandler.h'),
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_storage', 'ios', 'Classes', 'FLTFirebaseStoragePlugin.m')
  ]
  firebase_auth_patch_paths = [
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_auth', 'ios', 'Classes', 'FLTFirebaseAuthPlugin.m'),
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_auth', 'ios', 'Classes', 'Private', 'FLTAuthStateChannelStreamHandler.h'),
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_auth', 'ios', 'Classes', 'Private', 'FLTPhoneNumberVerificationStreamHandler.h'),
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_auth', 'ios', 'Classes', 'Private', 'PigeonParser.h'),
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_auth', 'ios', 'Classes', 'Public', 'FLTFirebaseAuthPlugin.h'),
    File.join(__dir__, '.symlinks', 'plugins', 'firebase_auth', 'ios', 'Classes', 'Private', 'FLTIdTokenChannelStreamHandler.h')
  ]

  firebase_storage_patch_paths.each do |path|
    next unless File.exist?(path)
    content = File.read(path)
    updated = content.gsub(
      '#import <Firebase/Firebase.h>',
      "@import FirebaseCore;\n@import FirebaseStorage;"
    ).gsub(
      "#import <FirebaseCore/FirebaseCore.h>\n#import <FirebaseStorage/FirebaseStorage.h>",
      "@import FirebaseCore;\n@import FirebaseStorage;"
    )
    next if updated == content
    FileUtils.chmod('u+w', path)
    File.write(path, updated)
  end

  firebase_auth_patch_paths.each do |path|
    next unless File.exist?(path)
    content = File.read(path)
    updated = content.gsub(
      '#import <Firebase/Firebase.h>',
      "@import FirebaseCore;\n@import FirebaseAuth;"
    ).gsub(
      "#import <FirebaseCore/FirebaseCore.h>\n#import <FirebaseAuth/FirebaseAuth.h>",
      "@import FirebaseCore;\n@import FirebaseAuth;"
    )
    next if updated == content
    FileUtils.chmod('u+w', path)
    File.write(path, updated)
  end
end
